spring.config.import=optional:configtree:/run/secrets/

# PROD application server
server.port=8083

# Default application database
spring.datasource.url=${PROD_DB_URL}
spring.datasource.username=${PROD_DB_USER}
spring.datasource.password=${PROD_DB_PWD}
spring.jpa.database-platform=org.hibernate.dialect.MariaDB103Dialect

# Thymeleaf
spring.thymeleaf.cache=true

# JPA
spring.jpa.hibernate.ddl-auto=update

# Logger
logging.level.com.poivredesiles.fundraising=INFO
logging.level.com.poivredesiles.fundraising.service=INFO

# Log path in container
logging.file.path=/var/log

# Mail with https enabled
spring.mail.host=box242.rapidenet.ca
spring.mail.port=587
spring.mail.username=webmestre@poivredesiles.com
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Actuator
#management.endpoints.enabled-by-default=false
#management.endpoints.jmx.exposure.exclude=*
#management.endpoint.info.enabled=true
#management.endpoint.health.enabled=true
#management.endpoint.sessions.enabled=true
#management.endpoint.loggers.enabled=true
#management.endpoint.metrics.enabled=true
#management.endpoint.scheduledtasks.enabled=true
#management.endpoint.logfile.enabled=true
3management.endpoints.web.exposure.include = info, health, sessions, loggers, logfile, metrics, scheduledtasks

# Spring Boot Admin
#spring.boot.admin.client.url=http://localhost:8085
#spring.boot.admin.client.instance.management-base-url=http://localhost:8083
#spring.boot.admin.client.instance.service-base-url=http://localhost:8083

# Task Executor
spring.task.execution.thread-name-prefix=autos-autos-task-
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=50
spring.task.execution.pool.queue-capacity=10000
spring.task.scheduling.thread-name-prefix=autos-autos-scheduling-
spring.task.scheduling.pool.size=2

# Application globals
application.baseUrl = financement.poivredesiles.com
application.admin.usernames= {'eva.maciejko', 'martin.cyr'}
application.admin.passwords={'$2a$10$mMsjrah9XGGErFG4wtCPJuhhCzb30arAn1vdMBQ2Vd8JoQfTtyeBa', '$2a$10$QUzHazWrfDhj9OUzaowEw.kzO85P9O6aATIFTrHmHbdmiq7K5Yq5y'}

application.mail.admin=emaciejko@gmail.com
application.mail.from=webmestre@poivredesiles.com
application.mail.cc=poivredesiles@videotron.ca
application.mail.to=leader
application.mail.pdi=poivredesiles@videotron.ca

keystore.filename= ${PROD_KEYSTORE_FILENAME}
keystore.password= ${PROD_KEYSTORE_PASSWORD}

# Global credentials
global.merchant.id = ${PROD_GLOBAL_MERCHANT_ID}
global.shared.secret = ${PROD_GLOBAL_SHARED_SECRET}
global.service.url = https://pay.realexpayments.com/pay
global.currency = CAD