# Default application database
spring.datasource.url=jdbc:mysql://localhost:3309/pdi?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JPA
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Logging
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# filemaker
application.filemaker.url = jdbc:filemaker://127.0.0.1/SW_Campagne
application.filemaker.username = UsagerJdbc
application.filemaker.password = 2021Poly