version: '3.9'

services:
    DEV-pdi-fundraising:
        image: daxyonis/pdi-fundraising:latest
        ports:
            - 8081:8081
        volumes:
            - dev-logs:/workspace/logs
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 3s
                max_attempts: 3
                window: 30s
            resources:
                limits:              
                    memory: 2048M
        secrets:
            - DB_USER
            - DB_PWD
            - DB_URL
            - EMAIL_PASSWORD
            - DEV_PAY_MERCHANT_ID
            - DEV_PAY_TOKEN
            - DEV_PAY_PRIVATE_TOKEN
            - KEYSTORE_PASSWORD
            - KEYSTORE_FILENAME
            
        environment:
            SPRING_PROFILES_ACTIVE: dev            
            JAVA_OPTS: "-Xms256m -Xmx768m -Xss512k -XX:MaxMetaspaceSize=128m -XX:MaxDirectMemorySize=64m"
            APPLICATION_ENCRYPTED: "true"
            APPLICATION_MODE_MAINTENANCE: "false"
            APPLICATION_ACTION_ENCRYPT: "false"
            LOGGING_FILE_PATH: "/workspace/logs"
    
    PROD-pdi-fundraising:
        image: daxyonis/pdi-fundraising:latest
        ports:
            - 8083:8083
        volumes:
            - prod-logs:/var/log
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 3s
                max_attempts: 3
                window: 30s
            resources:
                limits:              
                    memory: 1536M
        secrets:
            - PROD_DB_USER
            - PROD_DB_PWD
            - PROD_DB_URL
            - EMAIL_PASSWORD
            - PAY_MERCHANT_ID
            - PAY_TOKEN
            - PAY_PRIVATE_TOKEN
            - PROD_KEYSTORE_PASSWORD
            - PROD_KEYSTORE_FILENAME
                     
        environment:
            SPRING_PROFILES_ACTIVE: prod            
            JAVA_OPTS: "-Xms1024m -Xmx1024m"
            APPLICATION_ENCRYPTED: "true"
            APPLICATION_MODE_MAINTENANCE: "false"
            APPLICATION_ACTION_ENCRYPT: "false"

volumes: 
    dev-logs:
    prod-logs:
                
secrets:
  DB_USER:
    external: true
  DB_PWD:
    external: true 
  DB_URL:
    external: true 
  EMAIL_PASSWORD:
    external: true
  PAY_MERCHANT_ID:
    external: true
  PAY_TOKEN:
    external: true
  PAY_PRIVATE_TOKEN:
    external: true
  DEV_PAY_MERCHANT_ID:
    external: true
  DEV_PAY_TOKEN:
    external: true
  DEV_PAY_PRIVATE_TOKEN:
    external: true
  PROD_DB_USER:
    external: true 
  PROD_DB_PWD:
    external: true 
  PROD_DB_URL:
    external: true 
  KEYSTORE_PASSWORD:
    external: true
  KEYSTORE_FILENAME:
    external: true
  PROD_KEYSTORE_PASSWORD:
    external: true
  PROD_KEYSTORE_FILENAME:
    external: true